[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 補完系プラグイン
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
	source ~/.config/nvim/plugins/coc.rc.vim
'''

[[plugins]] # ランナー系プラグイン
repo = 'thinca/vim-quickrun'
hook_add = '''
	source ~/.config/nvim/plugins/quickrun.rc.vim
'''

[[plugins]] # 非同期実行
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # オープンブラウザー
repo = 'tyru/open-browser.vim'

[[plugins]] # ファインダー系プラグイン
repo = 'Shougo/denite.nvim'
hook_add = '''
	source ~/.config/nvim/plugins/denite.rc.vim
'''

#[[plugins]] # スタート画面カスタマイズ
#repo = 'mhinz/vim-startify'

#[[plugins]] # ステータスライン拡張
#repo = 'itchyny/lightline.vim'
#hook_add = '''
#	source ~/.config/nvim/plugins/lightline.rc.vim
#	'''

[[plugins]] # ファイラー系プラグイン
repo = 'Shougo/defx.nvim'
hook_add = '''
	source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]] # バッファー系プラグイン
repo = 'jlanzarotta/bufexplorer'

#[[plugins]] # Undo系プラグイン
#repo = 'simnalamburt/vim-mundo'
#hook_add = '''
#    source ~/.config/nvim/plugins/vim-mundo.rc.vim
#'''

[[plugins]] # 括弧編集系プラグイン
repo = 'tpope/vim-surround'

[[plugins]] # テキスト移動
repo = 't9md/vim-textmanip'
hook_add = '''
    source ~/.config/nvim/plugins/vim-textmanip.rc.vim
'''

[[plugins]] # タグの自動補完
repo = 'alvan/vim-closetag'
hook_add = '''
    source ~/.config/nvim/plugins/vim-closetag.rc.vim
'''

[[plugins]] # タグリスト表示
repo = 'preservim/tagbar'
hook_add = '''
	source ~/.config/nvim/plugins/tagbar.rc.vim
'''

[[plugins]] # ウィンドウサイジング
repo = 'simeji/winresizer'
hook_add = '''
    source ~/.config/nvim/plugins/winresizer.rc.vim
'''

[[plugins]] # バイナリエディター
repo = 'Shougo/vinarise.vim'
hook_add = '''
	source ~/.config/nvim/plugins/vinarise.rc.vim
'''


# Git系プラグイン#############
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    source ~/.config/nvim/plugins/vim-gitgutter.rc.vim
'''
############################


# 装飾系プラグイン#############
#[[plugins]] # カラースキーム
#repo = 'cocopon/iceberg.vim'
#hook_add = '''
#	source ~/.config/nvim/plugins/iceberg.rc.vim
#'''

[[plugins]] # iconセット
repo = 'ryanoasis/vim-devicons'

[[plugins]] # defxIcon
repo = 'kristijanhusak/defx-icons'

[[plugins]] # インデント可視化
repo = 'Yggdroot/indentLine'
hook_add = '''
	source ~/.config/nvim/plugins/indentLine.rc.vim
'''

[[plugins]] # 空白可視化
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
	source ~/.config/nvim/plugins/vim-trailing-whitespace.rc.vim
'''

[[plugins]] # 多言語パック
repo = 'sheerun/vim-polyglot'
hook_add = '''
	source ~/.config/nvim/plugins/vim-polyglot.rc.vim
'''

############################


# その他のプラグイン##########

[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = '''
    source ~/.config/nvim/plugins/vim-silicon.rc.vim
'''

############################
